### ISSUE TITLE
build fails on AArch64, Fedora 33 

### ISSUE THREAD

**Issue by LutzWeischerFujitsu** [Adlik/Adlik#422] opened 2021-03-11 12:57 UTC
[jw@cn06 adlik]$ bazel build //adlik_serving/clients/python:build_pip_package -c opt
WARNING: Output base '/home/jw/.cache/bazel/_bazel_jw/186654d637a0a781bc8858392a3e8812' is on NFS. This may lead to surprising failures and undetermined behavior.
INFO: Repository local_execution_config_python instantiated at:
  /home/jw/adlik/WORKSPACE:10:24: in <toplevel>
  /home/jw/adlik/adlik_serving/workspace.bzl:14:17: in adlik_serving_workspace
  /home/jw/.cache/bazel/_bazel_jw/186654d637a0a781bc8858392a3e8812/external/org_tensorflow/tensorflow/workspace.bzl:75:20: in tf_workspace
  /home/jw/.cache/bazel/_bazel_jw/186654d637a0a781bc8858392a3e8812/external/org_tensorflow/tensorflow/workspace.bzl:91:27: in tf_repositories
  /home/jw/.cache/bazel/_bazel_jw/186654d637a0a781bc8858392a3e8812/external/org_tensorflow/third_party/toolchains/remote_config/configs.bzl:6:28: in initialize_rbe_configs
  /home/jw/.cache/bazel/_bazel_jw/186654d637a0a781bc8858392a3e8812/external/org_tensorflow/third_party/toolchains/remote_config/rbe_config.bzl:158:27: in _tensorflow_local_config
Repository rule local_python_configure defined at:
  /home/jw/.cache/bazel/_bazel_jw/186654d637a0a781bc8858392a3e8812/external/org_tensorflow/third_party/py/python_configure.bzl:275:41: in <toplevel>
ERROR: An error occurred during the fetch of repository 'local_execution_config_python':
   Traceback (most recent call last):
        File "/home/jw/.cache/bazel/_bazel_jw/186654d637a0a781bc8858392a3e8812/external/org_tensorflow/third_party/py/python_configure.bzl", line 213, column 39, in _create_local_python_repository
                numpy_include = _get_numpy_include(repository_ctx, python_bin) + "/numpy"
        File "/home/jw/.cache/bazel/_bazel_jw/186654d637a0a781bc8858392a3e8812/external/org_tensorflow/third_party/py/python_configure.bzl", line 187, column 19, in _get_numpy_include
                return execute(
        File "/home/jw/.cache/bazel/_bazel_jw/186654d637a0a781bc8858392a3e8812/external/org_tensorflow/third_party/remote_config/common.bzl", line 217, column 13, in execute
                fail(
Error in fail: Problem getting numpy include path.
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ModuleNotFoundError: No module named 'numpy'
Is numpy installed?
INFO: Repository go_sdk instantiated at:
  /home/jw/adlik/WORKSPACE:18:16: in <toplevel>
  /home/jw/.cache/bazel/_bazel_jw/186654d637a0a781bc8858392a3e8812/external/com_github_grpc_grpc/bazel/grpc_extra_deps.bzl:36:27: in grpc_extra_deps
  /home/jw/.cache/bazel/_bazel_jw/186654d637a0a781bc8858392a3e8812/external/io_bazel_rules_go/go/toolchain/toolchains.bzl:379:28: in go_register_toolchains
  /home/jw/.cache/bazel/_bazel_jw/186654d637a0a781bc8858392a3e8812/external/io_bazel_rules_go/go/private/sdk.bzl:65:21: in go_download_sdk
Repository rule _go_download_sdk defined at:
  /home/jw/.cache/bazel/_bazel_jw/186654d637a0a781bc8858392a3e8812/external/io_bazel_rules_go/go/private/sdk.bzl:53:35: in <toplevel>
ERROR: Analysis of target '//adlik_serving/clients/python:build_pip_package' failed; build aborted: Problem getting numpy include path.
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ModuleNotFoundError: No module named 'numpy'
Is numpy installed?
INFO: Elapsed time: 0.884s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (2 packages loaded, 0 targets configured)
[jw@cn06 adlik]$ 

However, numpy is installed.

**Comment by KellyZhang2020** [comment] 2021-03-17 02:45
You need specify python3 path like:
```
env PYTHON_BIN_PATH=/usr/bin/python3 \
    bazel build //adlik_serving/clients/python:build_pip_package -c opt
```

and make sure numpy was installed in the `/usr/bin/python3`.

If build failed, try the follow command:
```
bazel build //adlik_serving/clients/python:build_pip_package -c opt --action_env=PYTHON_BIN_PATH=/usr/bin/python3
```

**Comment by LutzWeischerFujitsu** [comment] 2021-03-17 13:14
[jw@cn05 adlik]$ env PYTHON_BIN_PATH=/usr/bin/python3 \
>     bazel build //adlik_serving/clients/python:build_pip_package -c opt
WARNING: Output base '/home/jw/.cache/bazel/_bazel_jw/186654d637a0a781bc8858392a3e8812' is on NFS. This may lead to surprising failures and undetermined behavior.
Starting local Bazel server and connecting to it...
INFO: Analyzed target //adlik_serving/clients/python:build_pip_package (41 packages loaded, 949 targets configured).
INFO: Found 1 target...
ERROR: /home/jw/.cache/bazel/_bazel_jw/186654d637a0a781bc8858392a3e8812/external/zlib/BUILD.bazel:5:11: C++ compilation of rule '@zlib//:zlib' failed (Exit 1) gcc failed: error executing command /usr/lib64/ccache/gcc -U_FORTIFY_SOURCE -fstack-protector -Wall -Wunused-but-set-parameter -Wno-free-nonheap-object -fno-omit-frame-pointer -g0 -O2 '-D_FORTIFY_SOURCE=1' -DNDEBUG -ffunction-sections ... (remaining 25 argument(s) skipped)

Use --sandbox_debug to see verbose messages from the sandbox
ccache: error: Failed to create temporary file for /run/user/1001/ccache-tmp/tmp.cpp_stdout.UKvNlm: Read-only file system
Target //adlik_serving/clients/python:build_pip_package failed to build
Use --verbose_failures to see the command lines of failed build steps.
ERROR: /home/jw/adlik/adlik_serving/clients/python/BUILD:1:10 C++ compilation of rule '@zlib//:zlib' failed (Exit 1) gcc failed: error executing command /usr/lib64/ccache/gcc -U_FORTIFY_SOURCE -fstack-protector -Wall -Wunused-but-set-parameter -Wno-free-nonheap-object -fno-omit-frame-pointer -g0 -O2 '-D_FORTIFY_SOURCE=1' -DNDEBUG -ffunction-sections ... (remaining 25 argument(s) skipped)

Use --sandbox_debug to see verbose messages from the sandbox
INFO: Elapsed time: 253.161s, Critical Path: 2.18s
INFO: 62 processes: 61 internal, 1 linux-sandbox.
FAILED: Build did NOT complete successfully
[jw@cn05 adlik]$ bazel build //adlik_serving/clients/python:build_pip_package -c opt --action_env=PYTHON_BIN_PATH=/usr/bin/python3
WARNING: Output base '/home/jw/.cache/bazel/_bazel_jw/186654d637a0a781bc8858392a3e8812' is on NFS. This may lead to surprising failures and undetermined behavior.
INFO: Build option --action_env has changed, discarding analysis cache.
INFO: Analyzed target //adlik_serving/clients/python:build_pip_package (40 packages loaded, 949 targets configured).
INFO: Found 1 target...
ERROR: /home/jw/.cache/bazel/_bazel_jw/186654d637a0a781bc8858392a3e8812/external/zlib/BUILD.bazel:5:11: C++ compilation of rule '@zlib//:zlib' failed (Exit 1) gcc failed: error executing command /usr/lib64/ccache/gcc -U_FORTIFY_SOURCE -fstack-protector -Wall -Wunused-but-set-parameter -Wno-free-nonheap-object -fno-omit-frame-pointer -g0 -O2 '-D_FORTIFY_SOURCE=1' -DNDEBUG -ffunction-sections ... (remaining 25 argument(s) skipped)

Use --sandbox_debug to see verbose messages from the sandbox
ccache: error: Failed to create temporary file for /run/user/1001/ccache-tmp/tmp.cpp_stdout.cpVa0j: Read-only file system
Target //adlik_serving/clients/python:build_pip_package failed to build
Use --verbose_failures to see the command lines of failed build steps.
ERROR: /home/jw/adlik/adlik_serving/clients/python/BUILD:1:10 C++ compilation of rule '@zlib//:zlib' failed (Exit 1) gcc failed: error executing command /usr/lib64/ccache/gcc -U_FORTIFY_SOURCE -fstack-protector -Wall -Wunused-but-set-parameter -Wno-free-nonheap-object -fno-omit-frame-pointer -g0 -O2 '-D_FORTIFY_SOURCE=1' -DNDEBUG -ffunction-sections ... (remaining 25 argument(s) skipped)

Use --sandbox_debug to see verbose messages from the sandbox
INFO: Elapsed time: 5.199s, Critical Path: 1.70s
INFO: 51 processes: 51 internal.
FAILED: Build did NOT complete successfully
[jw@cn05 adlik]$ ls /usr/bin/python3/numpy*
ls: cannot access '/usr/bin/python3/numpy*': Not a directory
[jw@cn05 adlik]$ ls /usr/bin/python3
/usr/bin/python3
[jw@cn05 adlik]$ ls /usr/bin/python3 -al
lrwxrwxrwx 1 root root 9 Feb 21 00:53 /usr/bin/python3 -> python3.9
[jw@cn05 adlik]$ ls /usr/bin/python3.9
/usr/bin/python3.9
[jw@cn05 adlik]$ ls /usr/bin/python3.9 -al
-rwxr-xr-x 1 root root 68752 Feb 21 00:53 /usr/bin/python3.9
[jw@cn05 adlik]$ cd /usr/bin/python3.9
-bash: cd: /usr/bin/python3.9: Not a directory
[jw@cn05 adlik]$

**Comment by KellyZhang2020** [comment] 2021-03-19 07:04
I pull the Fedora docker images with version 33 using the command:
 `docker pull fedora`

Then I run the docker image:
`docker run -it fedora:latest bash`

In the docker container, do the following steps:
1. Configure network proxy
2. `dnf update`
3. `dnf install -y git`
4. `git clone https://github.com/ZTE/Adlik.git && cd Adlik/ `
5. `dnf install -y dnf-plugins-core`
6. `dnf copr enable vbatts/bazel`
7. `dnf install -y bazel4`
8. `dnf install -y automake libtool make  patch python3-numpy wich g++`
9. `env PYTHON_BIN_PATH=/usr/bin/python3 bazel build //adlik_serving/clients/python:build_pip_package -c opt`

Build completed successfully!

Your problem may caused by file permission errors. Shall you switch to user `root`, or building Adlik in the docker image (which is highly recommended ), so that Adlik wouldn't be disturbed in a clean environment.

**Comment by amadeus-zte** [comment] 2021-03-30 09:33
@LutzWeischerFujitsu  Do you have any conclusion?

**Comment by LutzWeischerFujitsu** [comment] 2021-04-01 10:40
Started fresh, it works now. However, another not: 

(base) [jw@cn05 adlik]$ bazel build //adlik_serving --config=tensorflow-cpu -c opt
...
external/org_tensorflow/tensorflow/core/kernels/ragged_tensor_to_tensor_op.cc:347:16: note: 'first_dimension' was declared here
  347 |     INDEX_TYPE first_dimension;
      |                ^~~~~~~~~~~~~~~
external/org_tensorflow/tensorflow/core/kernels/ragged_tensor_to_tensor_op.cc: In member function 'void tensorflow::{anonymous}::RaggedTensorToTensorBaseOp<INDEX_TYPE>::Compute(tensorflow::OpKernelContext*) [with INDEX_TYPE = int]':
external/org_tensorflow/tensorflow/core/kernels/ragged_tensor_to_tensor_op.cc:204:42: warning: 'first_dimension' may be used uninitialized in this function [-Wmaybe-uninitialized]
  204 |     for (INDEX_TYPE i = min_dimension; i < first_dimension; ++i) {
      |                                        ~~^~~~~~~~~~~~~~~~~
external/org_tensorflow/tensorflow/core/kernels/ragged_tensor_to_tensor_op.cc:347:16: note: 'first_dimension' was declared here
  347 |     INDEX_TYPE first_dimension;
      |                ^~~~~~~~~~~~~~~
ERROR: /home/jw/.cache/bazel/_bazel_jw/cbf5f9b738864a2966dae1480ea78f93/external/upb/BUILD:57:11: C++ compilation of rule '@upb//:upb' failed (Exit 1) gcc failed: error executing command /usr/bin/gcc -U_FORTIFY_SOURCE -fstack-protector -Wall -Wunused-but-set-parameter -Wno-free-nonheap-object -fno-omit-frame-pointer -g0 -O2 '-D_FORTIFY_SOURCE=1' -DNDEBUG -ffunction-sections ... (remaining 22 argument(s) skipped)

Use --sandbox_debug to see verbose messages from the sandbox
In file included from /usr/include/string.h:519,
                 from external/upb/upb/upb.h:16,
                 from external/upb/upb/upb.c:2:
In function 'strncpy',
    inlined from 'upb_status_seterrmsg' at external/upb/upb/upb.c:40:3:
/usr/include/bits/string_fortified.h:91:10: error: '__builtin_strncpy' specified bound 127 equals destination size [-Werror=stringop-truncation]
   91 |   return __builtin___strncpy_chk (__dest, __src, __len, __bos (__dest));
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
cc1: all warnings being treated as errors
Target //adlik_serving:adlik_serving failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 1759.614s, Critical Path: 735.64s
INFO: 2806 processes: 87 internal, 2719 linux-sandbox.
FAILED: Build did NOT complete successfully
(base) [jw@cn05 adlik]$ 

gcc 10.2.1

**Comment by KellyZhang2020** [comment] 2021-04-13 07:42
The reason is that tensorflow doesn't work on gcc 10 for now. You can downgrade the gcc version to 8.4.0 by following command:
```
1. Download the required installation package http://ftp.tsukuba.wide.ad.jp/software/gcc/releases/gcc-8.4.0/
2. tar -xvf gcc-8.4.0.tar.gz
3. cd gcc-8.4.0/
4. ./contrib/download_prerequisites
5. mkdir build
6. cd build
7. ../configure --prefix=/usr/local/gcc84 --program-suffix=84 --enable-languages=c,c++,fortran --disable-multilib --disable-libstdcxx-pch
8. make 
9. make install
```
Then switch gcc version from 10.2.1 to 8.4.0.
Finally `cd /Adlik `, build the TensorFlow-cpu serving by:
```
env PYTHON_BIN_PATH=/usr/bin/python3 \
        bazel build --config=tensorflow-cpu -c opt //adlik_serving
```

**Comment by amadeus-zte** [comment] 2021-04-14 10:14
@LutzWeischerFujitsu  Pls check @KellyZhang2020 solution.

**Comment by amadeus-zte** [comment] 2021-04-25 01:52
@LutzWeischerFujitsu 
I close this issue and if there is any other problem found, pls reopen it.

**Closed** 2021-05-25 11:36 UTC
